<a href="https://colab.research.google.com/github/akashms011-create/demo/blob/main/Pandascasestudy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#1,2
import numpy as np
import pandas as pd
data = pd.read_csv('/content/IMDB-Movie-Data.csv')
data

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Title               1000 non-null   object
 2   Genre               1000 non-null   object
 3   Description         1000 non-null   object
 4   Director            1000 non-null   object
 5   Actors              1000 non-null   object
 6   Year                1000 non-null   int64
 7   Runtime (Minutes)   1000 non-null   int64
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   int64
 10  Revenue (Millions)  872 non-null    float64
 11  Metascore           936 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 93.9+ KB

In [14]:
#3
print(data.shape)
print(data.head())
print(data.columns)
print(data.dtypes)
print(data.isnull().sum())

(1000, 12)
   Rank                    Title                     Genre  \
0     1  Guardians of the Galaxy   Action,Adventure,Sci-Fi
1     2               Prometheus  Adventure,Mystery,Sci-Fi
2     3                    Split           Horror,Thriller
3     4                     Sing   Animation,Comedy,Family
4     5            Suicide Squad  Action,Adventure,Fantasy

                                         Description              Director  \
0  A group of intergalactic criminals are forced ...            James Gunn
1  Following clues to the origin of mankind, a te...          Ridley Scott
2  Three girls are kidnapped by a man with a diag...    M. Night Shyamalan
3  In a city of humanoid animals, a hustling thea...  Christophe Lourdelet
4  A secret government agency recruits some of th...            David Ayer

                                              Actors  Year  Runtime (Minutes)  \
0  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014                121
1  Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012                124
2  James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016                117
3  Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016                108
4  Will Smith, Jared Leto, Margot Robbie, Viola D...  2016                123

   Rating   Votes  Revenue (Millions)  Metascore
0     8.1  757074              333.13       76.0
1     7.0  485820              126.46       65.0
2     7.3  157606              138.12       62.0
3     7.2   60545              270.32       59.0
4     6.2  393727              325.02       40.0
Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')
Rank                    int64
Title                  object
Genre                  object
Description            object
Director               object
Actors                 object
Year                    int64
Runtime (Minutes)       int64
Rating                float64
Votes                   int64
Revenue (Millions)    float64
Metascore             float64
dtype: object
Rank                    0
Title                   0
Genre                   0
Description             0
Director                0
Actors                  0
Year                    0
Runtime (Minutes)       0
Rating                  0
Votes                   0
Revenue (Millions)    128
Metascore              64
dtype: int64

In [17]:
#4
print("Duplicate rows before removal:", data.duplicated().sum())
data = data.drop_duplicates()

Duplicate rows before removal: 0

In [50]:
#5
data = data.rename(columns={"Title": "Movie_Title"})
data

,Rank,Movie_Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,Num_Genres,Profitability,Rating_Category,Custom_Score
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.130000,76.0,3,2.753140,Excellent,414.130000
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.460000,65.0,3,1.019839,Average,196.460000
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.120000,62.0,2,1.180513,Average,211.120000
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.320000,59.0,3,2.502963,Average,342.320000
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.020000,40.0,3,2.642439,Average,387.020000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,82.956376,45.0,3,0.747355,Average,144.956376
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.540000,46.0,1,0.186596,Poor,72.540000
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.010000,50.0,3,0.591939,Average,120.010000
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,82.956376,22.0,2,0.892004,Poor,138.956376
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.640000,11.0,3,0.225747,Poor,72.640000

In [28]:
#6
unique_genres = data['Genre'].str.split(',').explode().unique()
print("Unique Genres:\n", unique_genres)

Unique Genres:
 ['Action' 'Adventure' 'Sci-Fi' 'Mystery' 'Horror' 'Thriller' 'Animation'
 'Comedy' 'Family' 'Fantasy' 'Drama' 'Music' 'Biography' 'Romance'
 'History' 'Crime' 'Western' 'War' 'Musical' 'Sport']

In [29]:
#7
data['Num_Genres'] = data['Genre'].apply(lambda x: len(x.split(',')))
print("\nNumber of Genres per Movie:\n", data[['Movie_Title', 'Num_Genres']].head())

Number of Genres per Movie:
                Movie_Title  Num_Genres
0  Guardians of the Galaxy           3
1               Prometheus           3
2                    Split           2
3                     Sing           3
4            Suicide Squad           3

In [25]:
#8
data['Revenue (Millions)'] = data['Revenue (Millions)'].fillna(data['Revenue (Millions)'].mean())
data['Metascore'] = data['Metascore'].fillna(data['Metascore'].mean())

print("Missing values after handling:\n", data[['Revenue (Millions)', 'Metascore']].isnull().sum())

Missing values after handling:
 Revenue (Millions)    0
Metascore             0
dtype: int64

In [51]:
#9
top_5_rating = data.nlargest(5, 'Rating')[['Movie_Title', 'Rating']]
top_5_rating

         Movie_Title  Rating
54   The Dark Knight     9.0
80         Inception     8.8
117           Dangal     8.8
36      Interstellar     8.6
96     Kimi no na wa     8.6

In [33]:
#10
highest_revenue = data.loc[data['Revenue (Millions)'].idxmax()]
lowest_revenue = data.loc[data['Revenue (Millions)'].idxmin()]
print("\nHighest Revenue Movie:", highest_revenue['Movie_Title'], "-", highest_revenue['Revenue (Millions)'])
print("Lowest Revenue Movie:", lowest_revenue['Movie_Title'], "-", lowest_revenue['Revenue (Millions)'])

Highest Revenue Movie: Star Wars: Episode VII - The Force Awakens - 936.63
Lowest Revenue Movie: A Kind of Murder - 0.0

In [34]:
#11
avg_rating_director = data.groupby('Director')['Rating'].mean()
print("Avg Rating by Director (First 5):\n", avg_rating_director.head())

Avg Rating by Director (First 5):
 Director
Aamir Khan             8.5
Abdellatif Kechiche    7.8
Adam Leon              6.5
Adam McKay             7.0
Adam Shankman          6.3
Name: Rating, dtype: float64

In [52]:
#12
movies_per_year = data['Year'].value_counts().sort_index()
movies_per_year

Year
2006     44
2007     53
2008     52
2009     51
2010     60
2011     63
2012     64
2013     91
2014     98
2015    127
2016    297
Name: count, dtype: int64

In [53]:
#13
top_tier_movies = data[(data['Rating'] > 8) & (data['Revenue (Millions)'] > 100)]
top_tier_movies

,Rank,Movie_Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,Num_Genres,Profitability,Rating_Category,Custom_Score
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.000000,3,2.753140,Excellent,414.13
6,7,La La Land,"Comedy,Drama,Music",A jazz pianist falls for an aspiring actress i...,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",2016,128,8.3,258682,151.06,93.000000,3,1.180156,Excellent,234.06
36,37,Interstellar,"Adventure,Drama,Sci-Fi",A team of explorers travel through a wormhole ...,Christopher Nolan,"Matthew McConaughey, Anne Hathaway, Jessica Ch...",2014,169,8.6,1047747,187.99,74.000000,3,1.112367,Excellent,273.99
50,51,Star Wars: Episode VII - The Force Awakens,"Action,Adventure,Fantasy",Three decades after the defeat of the Galactic...,J.J. Abrams,"Daisy Ridley, John Boyega, Oscar Isaac, Domhna...",2015,136,8.1,661608,936.63,81.000000,3,6.886985,Excellent,1017.63
54,55,The Dark Knight,"Action,Crime,Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart,Mi...",2008,152,9.0,1791916,533.32,82.000000,3,3.508684,Excellent,623.32
67,68,Mad Max: Fury Road,"Action,Adventure,Sci-Fi",A woman rebels against a tyrannical ruler in p...,George Miller,"Tom Hardy, Charlize Theron, Nicholas Hoult, Zo...",2015,120,8.1,632842,153.63,90.000000,3,1.280250,Excellent,234.63
74,75,Zootopia,"Animation,Adventure,Comedy","In a city of anthropomorphic animals, a rookie...",Byron Howard,"Ginnifer Goodwin, Jason Bateman, Idris Elba, J...",2016,108,8.1,296853,341.26,78.000000,3,3.159815,Excellent,422.26
76,77,The Avengers,"Action,Sci-Fi",Earth's mightiest heroes must come together an...,Joss Whedon,"Robert Downey Jr., Chris Evans, Scarlett Johan...",2012,143,8.1,1045588,623.28,69.000000,2,4.358601,Excellent,704.28
77,78,Inglourious Basterds,"Adventure,Drama,War","In Nazi-occupied France during World War II, a...",Quentin Tarantino,"Brad Pitt, Diane Kruger, Eli Roth,Mélanie Laurent",2009,153,8.3,959065,120.52,69.000000,3,0.787712,Excellent,203.52
80,81,Inception,"Action,Adventure,Sci-Fi","A thief, who steals corporate secrets through ...",Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...",2010,148,8.8,1583625,292.57,74.000000,3,1.976824,Excellent,380.57
82,83,The Wolf of Wall Street,"Biography,Comedy,Crime","Based on the true story of Jordan Belfort, fro...",Martin Scorsese,"Leonardo DiCaprio, Jonah Hill, Margot Robbie,M...",2013,180,8.2,865134,116.87,75.000000,3,0.649278,Excellent,198.87
83,84,Gone Girl,"Crime,Drama,Mystery",With his wife's disappearance having become th...,David Fincher,"Ben Affleck, Rosamund Pike, Neil Patrick Harri...",2014,149,8.1,636243,167.74,79.000000,3,1.125772,Excellent,248.74
92,93,The Help,Drama,An aspiring author during the civil rights mov...,Tate Taylor,"Emma Stone, Viola Davis, Octavia Spencer, Bryc...",2011,146,8.1,342429,169.71,62.000000,1,1.162397,Excellent,250.71
99,100,The Departed,"Crime,Drama,Thriller",An undercover cop and a mole in the police att...,Martin Scorsese,"Leonardo DiCaprio, Matt Damon, Jack Nicholson,...",2006,151,8.5,937414,132.37,85.000000,3,0.876623,Excellent,217.37
114,115,Harry Potter and the Deathly Hallows: Part 2,"Adventure,Drama,Fantasy","Harry, Ron and Hermione search for Voldemort's...",David Yates,"Daniel Radcliffe, Emma Watson, Rupert Grint, M...",2011,130,8.1,590595,380.96,87.000000,3,2.930462,Excellent,461.96
124,125,The Dark Knight Rises,"Action,Thriller",Eight years after the Joker's reign of anarchy...,Christopher Nolan,"Christian Bale, Tom Hardy, Anne Hathaway,Gary ...",2012,164,8.5,1222645,448.13,78.000000,2,2.732500,Excellent,533.13
138,139,Shutter Island,"Mystery,Thriller","In 1954, a U.S. marshal investigates the disap...",Martin Scorsese,"Leonardo DiCaprio, Emily Mortimer, Mark Ruffal...",2010,138,8.1,855604,127.97,63.000000,2,0.927319,Excellent,208.97
144,145,Django Unchained,"Drama,Western","With the help of a German bounty hunter , a fr...",Quentin Tarantino,"Jamie Foxx, Christoph Waltz, Leonardo DiCaprio...",2012,165,8.4,1039115,162.80,81.000000,2,0.986667,Excellent,246.80
241,242,Inside Out,"Animation,Adventure,Comedy",After young Riley is uprooted from her Midwest...,Pete Docter,"Amy Poehler, Bill Hader, Lewis Black, Mindy Ka...",2015,95,8.2,416689,356.45,94.000000,3,3.752105,Excellent,438.45
427,428,The Bourne Ultimatum,"Action,Mystery,Thriller",Jason Bourne dodges a ruthless CIA official an...,Paul Greengrass,"Matt Damon, Edgar Ramírez, Joan Allen, Julia S...",2007,115,8.1,525700,227.14,85.000000,3,1.975130,Excellent,308.14
499,500,Up,"Animation,Adventure,Comedy",Seventy-eight year old Carl Fredricksen travel...,Pete Docter,"Edward Asner, Jordan Nagai, John Ratzenberger,...",2009,96,8.3,722203,292.98,88.000000,3,3.051875,Excellent,375.98
634,635,WALL·E,"Animation,Adventure,Family","In the distant future, a small waste-collectin...",Andrew Stanton,"Ben Burtt, Elissa Knight, Jeff Garlin, Fred Wi...",2008,98,8.4,776897,223.81,58.985043,3,2.283776,Excellent,307.81
645,646,Gran Torino,Drama,Disgruntled Korean War veteran Walt Kowalski s...,Clint Eastwood,"Clint Eastwood, Bee Vang, Christopher Carley,A...",2008,116,8.2,595779,148.09,58.985043,1,1.276638,Excellent,230.09
688,689,Toy Story 3,"Animation,Adventure,Comedy",The toys are mistakenly delivered to a day-car...,Lee Unkrich,"Tom Hanks, Tim Allen, Joan Cusack, Ned Beatty",2010,103,8.3,586669,414.98,92.000000,3,4.028932,Excellent,497.98
772,773,How to Train Your Dragon,"Animation,Action,Adventure",A hapless young Viking who aspires to hunt dra...,Dean DeBlois,"Jay Baruchel, Gerard Butler,Christopher Mintz-...",2010,98,8.1,523893,217.39,74.000000,3,2.218265,Excellent,298.39

In [54]:
#14
director_stats = data.groupby('Director').agg({
    'Rating': 'mean',
    'Revenue (Millions)': 'mean'
})
director_stats

                     Rating  Revenue (Millions)
Director
Aamir Khan             8.50            1.200000
Abdellatif Kechiche    7.80            2.200000
Adam Leon              6.50           82.956376
Adam McKay             7.00          109.535000
Adam Shankman          6.30           78.665000
...                     ...                 ...
Xavier Dolan           7.55           43.223188
Yimou Zhang            6.10           45.130000
Yorgos Lanthimos       7.20            4.405000
Zack Snyder            7.04          195.148000
Zackary Adler          5.10            6.530000

[644 rows x 2 columns]

In [55]:
#15
year_status = data.groupby('Year').agg({
    'Movie_Title': 'count',
    'Rating':'mean'
}).rename(columns={'Movie_Tilte': 'Movie_Count'})
year_status

      Movie_Title    Rating
Year
2006           44  7.125000
2007           53  7.133962
2008           52  6.784615
2009           51  6.960784
2010           60  6.826667
2011           63  6.838095
2012           64  6.925000
2013           91  6.812088
2014           98  6.837755
2015          127  6.602362
2016          297  6.436700

In [56]:
#16
data['Profitability'] = data['Revenue (Millions)'] / data['Runtime (Minutes)']
top_10_profitable = data.nlargest(10, 'Profitability')[['Movie_Title', 'Profitability']]
top_10_profitable

                                    Movie_Title  Profitability
50   Star Wars: Episode VII - The Force Awakens       6.886985
85                               Jurassic World       5.259516
119                                Finding Dory       5.013299
87                                       Avatar       4.694506
76                                 The Avengers       4.358601
15                      The Secret Life of Pets       4.233448
688                                 Toy Story 3       4.028932
12                                    Rogue One       4.001278
174                                      Frozen       3.928824
797                             Despicable Me 2       3.755612

In [57]:
#17
def categorize_rating(rating):
    if rating < 6:
        return 'Poor'
    elif 6 <= rating < 7.5:
        return 'Average'
    else:
        return 'Excellent'
data['Rating_Category'] = data['Rating'].apply(categorize_rating)
data['Rating_Category']

0      Excellent
1        Average
2        Average
3        Average
4        Average
         ...
995      Average
996         Poor
997      Average
998         Poor
999         Poor
Name: Rating_Category, Length: 1000, dtype: object

In [47]:
#18
def calculate_score(row):
    return (row['Rating'] * 10) + row['Revenue (Millions)']
data['Custom_Score'] = data.apply(calculate_score, axis=1)

print("Custom Scores:\n", data[['Movie_Title', 'Rating', 'Revenue (Millions)', 'Custom_Score']].head())

Custom Scores:
                Movie_Title  Rating  Revenue (Millions)  Custom_Score
0  Guardians of the Galaxy     8.1              333.13        414.13
1               Prometheus     7.0              126.46        196.46
2                    Split     7.3              138.12        211.12
3                     Sing     7.2              270.32        342.32
4            Suicide Squad     6.2              325.02        387.02